-- 关闭总开关后使用本轮改造前的 R7 路径；开关变更通过新对局生效。
local C = {
	ENABLED = true, PUSH = true, ROAM = true, LOCAL_FALLBACK = true,
	DEBUG = true, RUN_ID = 'EXECUTION-CONTRACT-20261003-R28',
	RECOVERY_STEP_FINISH_SECONDS = 2.5,
	PROGRESS_VALUE_SECONDS=2, PROGRESS_VALUE_BONUS=0.04, PROGRESS_VALUE_CAP=0.92,
	LEAVE_PROGRESS_COST=0.15, ORDINARY_DEFEND_CREEPS_CAP=0.62, ORDINARY_DEFEND_HEROES_CAP=0.88,
	SAFE_RETURN_DESIRE=0.12, SAFE_RETURN_CONFIRM_SECONDS=2, CROSS_LANE_PROGRESS_COST=0.10,
	RUNE_RESUME_SECONDS=2,
	MAP_RESOURCES_ENABLED=true, MAP_RESOURCE_OBSERVATION_TTL=2.5,
	LOTUS_DESIRE=0.30, LOTUS_MAX_DISTANCE=2500, LOTUS_TASK_SECONDS=15,
	LOTUS_NEAR_DESIRE=0.72, LOTUS_CLAIM_DESIRE=0.97, LOTUS_MAX_CLAIMS=2,
	BASIC_LANE = true, BASIC_LANE_DESIRE = 0.15,
	PLAN_INTERVAL = 0.75, CANDIDATE_TTL = 1.0, LOG_INTERVAL = 2.0,
	GAP_SECONDS = 1.0, FALLBACK_DESIRE = 0.18,
	FALLBACK_INTERVAL = 1.0, FALLBACK_DURATION = 6.0,
	LOCAL_ROUTE_MAX_CHECKS = 18,
}
function C.PushEnabled() return C.ENABLED and C.PUSH end
function C.RoamEnabled() return C.ENABLED and C.ROAM end
function C.FallbackEnabled() return C.RoamEnabled() and C.LOCAL_FALLBACK end
function C.BasicLaneEnabled() return C.PushEnabled() and C.BASIC_LANE end
return C
