local RoamConfig = {}

-- 新 gank 框架默认关闭；现有持续施法、连招和拾取逻辑不受此开关影响。
RoamConfig.ENABLED = true
RoamConfig.DEBUG = false
RoamConfig.ANNOUNCE_CHAT = true

RoamConfig.LANING_PHASE_END_TIME = 8 * 60
RoamConfig.APPROACH_TIMEOUT = 12.0
RoamConfig.ENGAGE_TIMEOUT = 12.0
RoamConfig.MISSION_TIMEOUT = 22.0
RoamConfig.ANNOUNCEMENT_WINDOW = 4.0
RoamConfig.ANNOUNCEMENT_TARGET_RADIUS = 900
RoamConfig.LOST_TARGET_GRACE = 2.5
RoamConfig.TEAM_COOLDOWN = 30.0
RoamConfig.MAX_ROAMERS = 2
RoamConfig.PARTICIPANT_JOIN_TIMEOUT = 4.0
RoamConfig.EARLY_ROAM_LEVEL = 5
RoamConfig.EARLY_ROAM_MAX_TRAVEL_TIME = 8.0
RoamConfig.EARLY_ROAM_TEAM_COOLDOWN = 45.0
RoamConfig.EARLY_ROAM_MAX_ROAMERS = 1
RoamConfig.EARLY_ROAM_OUTNUMBER_TARGET_HEALTH = 0.65
RoamConfig.EARLY_ROAM_KILL_CONFIRM_HEALTH = 0.30
RoamConfig.EARLY_ROAM_MIN_KILL_POWER_RATIO = 1.10

RoamConfig.LANE_DISTANCE = 900
RoamConfig.LOCAL_FIGHT_RADIUS = 1600
RoamConfig.TOWER_DANGER_RADIUS = 1200
RoamConfig.ENGAGE_DISTANCE = 900
RoamConfig.MIN_START_POWER_RATIO = 0.90
RoamConfig.MIN_CONTINUE_POWER_RATIO = 0.80
RoamConfig.INITIATION_TIMEOUT = 1.5
RoamConfig.MIN_TARGET_SCORE = 0.35
RoamConfig.OUTNUMBER_TARGET_MIN_POWER_RATIO = 1.10
RoamConfig.TARGET_LOCAL_DAMAGE_FACTOR = 0.55
RoamConfig.TARGET_ARRIVAL_BUFFER = 0.75
RoamConfig.TARGET_TTK_BONUS_WINDOW = 6.0
RoamConfig.RALLY_UPDATE_LOG_DISTANCE = 300
RoamConfig.RALLY_UPDATE_LOG_INTERVAL = 1.0
RoamConfig.PURSUIT_SAMPLE_INTERVAL = 0.5
RoamConfig.PURSUIT_ESCAPE_DISTANCE = 120
RoamConfig.PURSUIT_MIN_TARGET_DISTANCE = 650
RoamConfig.PURSUIT_SWITCH_DISTANCE = 1100
RoamConfig.PURSUIT_SWITCH_MARGIN = 0.10
RoamConfig.PURSUIT_RETREAT_POWER_RATIO = 0.75
RoamConfig.PURSUIT_RETREAT_HEALTH_FRACTION = 0.35
RoamConfig.PURSUIT_KEEP_TARGET_HEALTH_FRACTION = 0.28
RoamConfig.TP_MIN_WALK_DISTANCE = 4200
RoamConfig.TP_MAX_LANDING_DISTANCE = 2600
RoamConfig.TP_CHANNEL_TIME_ESTIMATE = 3.0
RoamConfig.TP_MIN_TIME_SAVING = 1.5
RoamConfig.TP_SAFE_RADIUS = 1200
RoamConfig.TP_CAST_START_GRACE = 1.0
RoamConfig.TP_LANDING_OBSERVED_RADIUS = 600
RoamConfig.TP_REPLAN_LOG_DISTANCE = 200
RoamConfig.COMBAT_LOG_INTERVAL = 1.0
RoamConfig.COMBAT_HEALTH_LOG_MIN_DELTA = 1.0

RoamConfig.POSITION_RULES = {
	mid = {
		minLevel = 6,
		minHealth = 0.70,
		minMana = 0.50,
		travelBias = 2.0,
	},
	soft_support = {
		minLevel = 4,
		minHealth = 0.60,
		minMana = 0.40,
		travelBias = 0.0,
	},
	hard_support = {
		minLevel = 5,
		minHealth = 0.60,
		minMana = 0.40,
		travelBias = 1.0,
	},
}

local REQUIRED_POSITIVE_NUMBERS = {
	"LANING_PHASE_END_TIME",
	"APPROACH_TIMEOUT",
	"ENGAGE_TIMEOUT",
	"MISSION_TIMEOUT",
	"ANNOUNCEMENT_WINDOW",
	"ANNOUNCEMENT_TARGET_RADIUS",
	"LOST_TARGET_GRACE",
	"TEAM_COOLDOWN",
	"MAX_ROAMERS",
	"PARTICIPANT_JOIN_TIMEOUT",
	"EARLY_ROAM_LEVEL",
	"EARLY_ROAM_MAX_TRAVEL_TIME",
	"EARLY_ROAM_TEAM_COOLDOWN",
	"EARLY_ROAM_MAX_ROAMERS",
	"EARLY_ROAM_OUTNUMBER_TARGET_HEALTH",
	"EARLY_ROAM_KILL_CONFIRM_HEALTH",
	"EARLY_ROAM_MIN_KILL_POWER_RATIO",
	"LANE_DISTANCE",
	"LOCAL_FIGHT_RADIUS",
	"TOWER_DANGER_RADIUS",
	"ENGAGE_DISTANCE",
	"MIN_START_POWER_RATIO",
	"MIN_CONTINUE_POWER_RATIO",
	"INITIATION_TIMEOUT",
	"MIN_TARGET_SCORE",
	"OUTNUMBER_TARGET_MIN_POWER_RATIO",
	"TARGET_LOCAL_DAMAGE_FACTOR",
	"TARGET_ARRIVAL_BUFFER",
	"TARGET_TTK_BONUS_WINDOW",
	"RALLY_UPDATE_LOG_DISTANCE",
	"RALLY_UPDATE_LOG_INTERVAL",
	"PURSUIT_SAMPLE_INTERVAL",
	"PURSUIT_ESCAPE_DISTANCE",
	"PURSUIT_MIN_TARGET_DISTANCE",
	"PURSUIT_SWITCH_DISTANCE",
	"PURSUIT_SWITCH_MARGIN",
	"PURSUIT_RETREAT_POWER_RATIO",
	"PURSUIT_RETREAT_HEALTH_FRACTION",
	"PURSUIT_KEEP_TARGET_HEALTH_FRACTION",
	"TP_MIN_WALK_DISTANCE",
	"TP_MAX_LANDING_DISTANCE",
	"TP_CHANNEL_TIME_ESTIMATE",
	"TP_MIN_TIME_SAVING",
	"TP_SAFE_RADIUS",
	"TP_CAST_START_GRACE",
	"TP_LANDING_OBSERVED_RADIUS",
	"TP_REPLAN_LOG_DISTANCE",
	"COMBAT_LOG_INTERVAL",
	"COMBAT_HEALTH_LOG_MIN_DELTA",
}

local function IsFiniteNumber(value)
	return type(value) == "number" and value == value and value > 0
end

local function IsValidPositionRule(rule)
	return type(rule) == "table"
		and IsFiniteNumber(rule.minLevel)
		and IsFiniteNumber(rule.minHealth) and rule.minHealth <= 1
		and IsFiniteNumber(rule.minMana) and rule.minMana <= 1
		and type(rule.travelBias) == "number" and rule.travelBias == rule.travelBias
		and rule.travelBias >= 0
end

function RoamConfig.IsEnabled()
	if RoamConfig.ENABLED ~= true
		or type(RoamConfig.DEBUG) ~= "boolean"
		or type(RoamConfig.ANNOUNCE_CHAT) ~= "boolean"
		or type(RoamConfig.POSITION_RULES) ~= "table"
	then
		return false
	end
	for _, field in ipairs(REQUIRED_POSITIVE_NUMBERS) do
		if not IsFiniteNumber(RoamConfig[field]) then return false end
	end
	if RoamConfig.EARLY_ROAM_OUTNUMBER_TARGET_HEALTH > 1
		or RoamConfig.EARLY_ROAM_KILL_CONFIRM_HEALTH > RoamConfig.EARLY_ROAM_OUTNUMBER_TARGET_HEALTH
		or RoamConfig.EARLY_ROAM_MAX_ROAMERS > RoamConfig.MAX_ROAMERS
	then
		return false
	end
	return IsValidPositionRule(RoamConfig.POSITION_RULES.mid)
		and IsValidPositionRule(RoamConfig.POSITION_RULES.soft_support)
		and IsValidPositionRule(RoamConfig.POSITION_RULES.hard_support)
end

return RoamConfig
