-- 独立配置；研究能力默认关闭，日志字段保持兼容。
return {
	PROBE_MODE_LOAD = false,
	PROBE_PHASE = 0,
	PROBE_TARGET_TEAM = TEAM_RADIANT,
	USE_NATIVE_ZONES = false,
	USE_NATIVE_REMOVE = false,
	USE_NATIVE_PATH = false,
	EXECUTE_NATIVE_PATH = false,
	NATIVE_ZONE_TTL = 0.75,
	NATIVE_ZONE_REFRESH = 0.50,
	PATH_TIMEOUT = 0.25,
	HANDOFF_FALLBACK_STALL_PROBE = false,
	HANDOFF_FALLBACK_STALL_PROBE_HOLD_TIME = 1.60,
	PROBE_MODE_LOAD_HOLD = 1.00,
}
